# Generated by Django 4.2.8 on 2023-12-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_no',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
